foreground #5A2EFF
background #06030d
selection_background #7F70FF 
cursor #7F70FF
cursor_text_color #0c0512  

color0  #0c0512
color1  #5A2EFF
color2  #5A2EFF
color3  #7F70FF
color4  #5A2EFF
color5  #5A2EFF
color6  #7F70FF
color7  #5A2EFF
color8  #7F70FF
color9  #5A2EFF
color10 #5A2EFF
color11 #7F70FF
color12 #5A2EFF
color13 #5A2EFF
color14 #7F70FF
color15 #5A2EFF

background_opacity 0.85

font_family JetBrainsMono Nerd Font
font_size 13.0

shell zsh
